### ISSUE TITLE
Setting permissions with no permission systems in place.

### ISSUE THREAD

**Issue by planetWayne** [maker-dude/EpicZones#13]
Hi,
Hopefully a real simple one.
I run a small server with very few players and have found EpicZones useful for stopping mobs take out players in spawn area and zones of interest (portal jump points etc). Because of this there is only one Op (me) - all the rest are normal players so I haven't found the need so far to use any permission systems. Normal players can't use op commands or '/give' any extra materials so all good there.

The problem I have is that I cant seem to set any permissions to stop anyone destroying or building blocks in any created zones. Is it possible to set deny permissions without using any permission systems? (ie a default vanilla bukkit installation)

Thanks
Wayne.

**Comment by CourtArtanis** [comment]
EZ does have internal permissions, but it is group based (based on the groups you have setup in an external perms plugin).

Look in the plugins/EpicZones/config.yml and you should see:

globalZoneDefaultBuild: true,
globalZoneDefaultDestroy: true

This sets all group/action permissions to the value you give, set it to false to disallow any player from build/destroy (unless you set it up in the zone configs to override it)

Let me know how that works out for you.

**Comment by maker-dude** [comment]
If you are not using any permissions systems, EZ will treat everybody with OP access as though they are in the "op" group, and everybody else as though they are in the 'default' group. So if you want to stop everybody but ops, then use the 'default' group for restricting block place/break.

Otherwise you need to do it on a per player basis, instead of a group.

**Comment by planetWayne** [comment]
Hi both,
Thanks for the replies, I've got around the problem at the min by setting the global.ZoneDefaultBuild etc options that CourtArtanis suggested.

Presently, my account is OP on the server and I can still break or make blocks - no issue there, others cannot do either (as you would expect). I must admit I did try setting 'default' a perm but it didn't seem to work. (I must admit - I'm sure I tried 'default' and not 'Default' but I'll go and check)

May I make a small suggestion with respect to setting ceiling and floor levels? - How about a relative number based on player position? e.g. /zone floor -10 or /zone ceiling +10 (note the addition of a +- sign would be needed) then either value is just calculated where a player stands.

(Just a small point - but great plug in - managed to protect some teleporters and spawn points really easily.)

Thanks
Wayne.

**Comment by maker-dude** [comment]
Glad to hear this is working for you now. I'll look into why default might not have been working for you. As for the suggestion to change the floor/ceiling i like it, but don't want to forget about it. would you mind creating a new task asking for that enhancement?
